### ISSUE TITLE
RelatedViewModelField improvements/fixes

### ISSUE THREAD

**Issue by davecoates** [prestojs/prestojs#82]
- [x] Export from index.ts
- [x] Support lists of values. Probably requires support for lists in general for the source field to work
- [ ] `ViewModelCache.getAll` doesn't seem to support getting related fields, at least not properly eg. `cache.getAll([['operator', 'id']])` works but `cache.getAll([['operator', 'abbreviatedName']])` doesn't despite the field existing (and it works if you call `.get(id, ...)`

**Comment by levic** [comment]
eg: serializer with many=True, returns multiple records

Current implementation of RelatedViewModelField doesn't support multiple fields, need some way to handle this (either new field or same field with a many=true prop)
